name: Update node modules cache

on:
  push:
    branches:
    - master

jobs:
  build_cache:
    name: Build cache
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: './.github/actions/setup_node'
        
      # Improved caching strategy with restore keys for fallback
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: node_modules-cache-${{ runner.os }}-${{ hashFiles('package-lock.json', 'packages/*/package.json') }}
          restore-keys: |
            node_modules-cache-${{ runner.os }}-
            node_modules-cache-
            
      # Only run npm install if cache miss
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install dependencies
        uses: "./.github/actions/npm_install_from_cache"